name: Test
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: v1.1.0
        type: string

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Fetch Tags
        run: |
          git fetch --tags
          git fetch --prune --unshallow || true

      - name: Parse Versions
        id: previous_version
        shell: pwsh
        run: |
          Function Append-Output {
            $Key = $Args[0]
            $Value = $Args[1..$Args.Length] -Join " "

            Write-Output "$Key=$Value`n" >> $Env:GITHUB_OUTPUT
          }

          Function Get-Previous-Tag {
            param(
              [string]$Prefix = ""
            )

            return git for-each-ref --sort=-creatordate --count 1 --format="%(refname:short)" "refs/tags/$Prefix*"
          }

          $Version = "${{ inputs.version }}".Substring(1).Split(".")
          $VersionWithoutPatch = "v$($Version[0]).$($Version[1])"
          $PreviousVersion = Get-Previous-Tag $VersionWithoutPatch

          Write-Host $VersionWithoutPatch
          Write-Host $PreviousVersion

          Append-Output version $($Version -Join ".")
          Append-Output major $Version[0]
          Append-Output minor $Version[1]
          Append-Output patch $Version[2]

      - name: Tests
        shell: pwsh
        run: |
          Function Parse-Version {
            param(
              [string]$Version
            )

            if ($Version.StartsWith("v")) {
              $Version = $Version.Substring(1)
            }

            return $Version.Split(".")
          }

          $CurrentVersion = Parse-Version "${{ inputs.version }}"

          Write-Host Version: ($CurrentVersion -Join ".")
          Write-Host Previous Version: ${{ steps.previous_version.outputs.version }}
