name: Test
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: v1.1.0
        type: string

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Parse Versions
        id: version
        shell: pwsh
        run: |
          Function Append-Output {
            $Key = $Args[0]
            $Value = $Args[1..$Args.Length] -Join " "

            Write-Output "$Key=$Value`n" >> $Env:GITHUB_OUTPUT
          }

          Function Get-Previous-Tag {
            param(
              [string]$Prefix = ""
            )

            return (git tag -l --sort=-creatordate)[0]
            # return git for-each-ref --sort=-creatordate --count 1 --format="%(refname:short)" "refs/tags/*"
          }

          $PreviousVersion = Get-Previous-Tag v
          Write-Host $PreviousVersion

          $Version = "${{ inputs.version }}".Substring(1).Split(".")

          Append-Output major $Version[0]
          Append-Output minor $Version[1]
          Append-Output patch $Version[2]

      - name: Get Previous Version
        id: previous_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          prefix: v
          fallback: v1.0.0

      - name: Tests
        shell: pwsh
        run: |
          Function Parse-Version {
            param(
              [string]$Version
            )

            return $Version.Substring(1).Split(".")
          }

          $CurrentVersion = Parse-Version "${{ inputs.version }}"
          $PreviousVersion = Parse-Version "${{ steps.previous_tag.outputs.tag }}"

          Write-Host Version: ($CurrentVersion -Join ".")
          Write-Host Previous Version: ($PreviousVersion -Join ".")

          Write-Host Major: ${{ steps.version.outputs.major }}
          Write-Host Minor: ${{ steps.version.outputs.minor }}
          Write-Host Patch: ${{ steps.version.outputs.patch }}
